apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: stting/baby
      context: ../baby
      jib: {}
    - image: stting/gateway
      context: ../gateway
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
