apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baby-postgresql-pvc
  namespace: mamazinha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: baby-postgresql
  namespace: mamazinha
  labels:
    app: baby-postgresql
type: Opaque
data:
  postgresql-password: MGNkZjcyMzJmMTk4MTFmYTFmNzg4MTg4ODAyNTc1MWNjMzViZmViMmQ4OTAzNWZiNDliYTkyZGI1ZTJm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baby-postgresql
  namespace: mamazinha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baby-postgresql
  template:
    metadata:
      labels:
        app: baby-postgresql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: baby-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:13.4
          env:
            - name: POSTGRES_USER
              value: baby
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: baby-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: baby-postgresql
  namespace: mamazinha
spec:
  selector:
    app: baby-postgresql
  ports:
    - port: 5432
